name: Create Article

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,10 * * *"

defaults:
  run:
    working-directory: scripts

jobs:
  create_article:
    name: Create Article
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: main process
        env:
          TZ: Asia/Tokyo
          MICROCMS_API_DOMAIN: ${{ secrets.MICROCMS_API_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        run: node createArticle.js
